### ISSUE TITLE
Crash 1.17.1

### ISSUE THREAD

**Issue by xg787** [PTOM76/uncraftingtable-fabric#2]
[crash-2021-10-09_16.46.06-client.txt](https://github.com/PTOM76/uncraftingtable-fabric/files/7316386/crash-2021-10-09_16.46.06-client.txt)

**Comment by stevojhall** [comment]
I'm using the 1.18.1 branch and am also getting this issue.

to reproduce this I was changing the output recipe and came across the crash consistently.

https://pastebin.com/mAUqvLrj

**Comment by PTOM76** [comment]
Thank you for your reporting
Fixed
https://www.curseforge.com/minecraft/mc-mods/simple-uncrafting-table-fabric/files/3724124
