### ISSUE TITLE
Server Crash - 1.18.2

### ISSUE THREAD

**Issue by drew-id** [PTOM76/uncraftingtable-fabric#5]
Hi,

Server locks up and crashes upon attempting to open the table.
Packet issues communicating with the server perhaps?
Server logs below with crash details - let me know if you need more info or client logs. Checked client but nothing i could find in the logs. 

Also works perfectly in Single Player without any issues i discovered.

I forked your repo to do some testing if i get time

https://pastebin.com/LF8NMybe

Regards,
Drew-ID

**Comment by PTOM76** [comment]
Thank you for your reporting
Fixed
https://www.curseforge.com/minecraft/mc-mods/simple-uncrafting-table-fabric/files/3724124
