### ISSUE TITLE
Hey, this is just a quick bug report to tell you that your table gives back full resources for nearly broken tools.

### ISSUE THREAD

**Issue by G93d14** [PTOM76/uncraftingtable-fabric#7]
何時でも折れろそうな　金の刀剣も　金のインゴットの二つも、すてィっくの一本も　とりかえられるそう。使用目的なものでしたら、失礼いたしましたので、もうしわけございません。ぜひ、この　レポっとを　軽視してください。

The uncrafting bench can return two gold ingots and one stick even for nearly broken swords. if this is intended behaviour, please ignore this report.

日本語というのは、まだ勉強中ので、なにか文法で間違いでしたらも、ご勘弁をもらえるように、お願いいたします。

![2022-06-04_15 18 02](https://user-images.githubusercontent.com/54314688/171994617-ae1fbd39-1c3c-473c-b101-a377b6a395a0.png)

**Comment by PTOM76** [comment]
This is a intended behavior.
However, add it and I would like to be able to change it in the settings if I have time.

**Comment by PTOM76** [comment]
I will be able to set it while supporting Forge.
